export enum E_WORKER_PROCESS {
  FISCAL_OBLIGATIONS_EVENTS_PACKAGE = "fiscalObligationsEventsPackage"
}

export enum E_OBRIGACOES {
  EFINANCEIRA  = 'efinanceira',
  REINF        = 'reinf',
  ESOCIAL      = 'esocial',
  NFSE         = 'nota_fiscal_eletronica'
}


export enum E_OBRIGACOES_CODIGO_LAYOUT {
  EFINANCEIRA_CADASTRO_DECLARANTE     = '001',
  EFINANCEIRA_ABERTURA                = '002',
  EFINANCEIRA_MOVIMENTACAO_FINANCEIRA = '003',
  EFINANCEIRA_PREVIDENCIA_PRIVADA     = '004',
  EFINANCEIRA_FECHAMENTO              = '005',
  EFINANCEIRA_EXCLUSAO                = '006',
  EFINANCEIRA_CADASTRO_PATROCINADOS   = '008',
  EFINANCEIRA_EXCLUSAO_TOTAL          = '009',
  EFINANCEIRA_REPASSE_ABERTURA        = '012',
  EFINANCEIRA_REPASSE_FECHAMENTO      = '013',
  EFINANCEIRA_REPASSE_MOVIMENTO       = '014',
}